version: "3"
services:
  phpfpm:
    image: "registry.cn-hangzhou.aliyuncs.com/marhal/php-7.4.26:v1.0.1"
    links:
      - mysql
    volumes:
      - ./:/var/www/html/:cached
    cap_add:
      - SYS_PTRACE
    environment:
        - APP_ENV=dev
    networks:
        - database
        - default
        - application
    container_name: marhal-phpfpm
  mysql:
    image: "registry.cn-hangzhou.aliyuncs.com/marhal/mysql-5.7:v1.0.0"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - database
    container_name: marhal-mysql
  nginx:
    image: "registry.cn-hangzhou.aliyuncs.com/marhal/nginx-official:v1.0.1"
    ports:
      - "18010:80"
    links:
      - "phpfpm"
    volumes:
      - ./:/var/www/html/
    networks:
      - application
      - default
    container_name: marhal-nginx
networks:
  database:
    external: true
  application:
    external: true