version: "3"
services:
  phpfpm:
    image: "registry.cn-hangzhou.aliyuncs.com/marhal/php-7.4.26:v1.0.0"
    links:
      - mysql
    volumes:
      - ./:/var/www/html/:cached
    cap_add:
      - SYS_PTRACE
    environment:
        - APP_ENV=zkgj-dev
        - TZ=Asia/Shanghai
        - TIME_ZONE=Asia/Shanghai
    networks:
        - phpfpm-mysql
        - default
        - nginx-phpfpm
    container_name: marhal-phpfpm
  mysql:
    image: "registry.cn-hangzhou.aliyuncs.com/marhal/mysql-5.7:v1.0.0"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
      - TIME_ZONE=Asia/Shanghai
    networks:
      - phpfpm-mysql
    container_name: marhal-mysql
  nginx:
    image: "registry.cn-hangzhou.aliyuncs.com/marhal/nginx-official:v1.0.2"
    ports:
      - "18010:80"
    environment:
      - TZ=Asia/Shanghai
      - TIME_ZONE=Asia/Shanghai
    links:
      - "phpfpm"
    volumes:
      - ./:/var/www/html/
    networks:
      - nginx-phpfpm
      - default
    container_name: marhal-nginx
networks:
  phpfpm-mysql:
    external: true
  nginx-phpfpm:
    external: true